// Code generated by entc, DO NOT EDIT.

package infectedrecord

const (
	// Label holds the string label denoting the infectedrecord type in the database.
	Label = "infected_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReportedDate holds the string denoting the reporteddate field in the database.
	FieldReportedDate = "reported_date"
	// FieldCollectedDate holds the string denoting the collecteddate field in the database.
	FieldCollectedDate = "collected_date"
	// FieldPcrTotalTests holds the string denoting the pcrtotaltests field in the database.
	FieldPcrTotalTests = "pcr_total_tests"
	// FieldPrTotalTests holds the string denoting the prtotaltests field in the database.
	FieldPrTotalTests = "pr_total_tests"
	// FieldAgTotalTests holds the string denoting the agtotaltests field in the database.
	FieldAgTotalTests = "ag_total_tests"
	// FieldPcrPositiveTests holds the string denoting the pcrpositivetests field in the database.
	FieldPcrPositiveTests = "pcr_positive_tests"
	// FieldPrPositiveTests holds the string denoting the prpositivetests field in the database.
	FieldPrPositiveTests = "pr_positive_tests"
	// FieldAgPositiveTests holds the string denoting the agpositivetests field in the database.
	FieldAgPositiveTests = "ag_positive_tests"

	// EdgePlaces holds the string denoting the places edge name in mutations.
	EdgePlaces = "places"

	// Table holds the table name of the infectedrecord in the database.
	Table = "infected_records"
	// PlacesTable is the table the holds the places relation/edge. The primary key declared below.
	PlacesTable = "infected_record_places"
	// PlacesInverseTable is the table name for the Place entity.
	// It exists in this package in order to avoid circular dependency with the "place" package.
	PlacesInverseTable = "places"
)

// Columns holds all SQL columns for infectedrecord fields.
var Columns = []string{
	FieldID,
	FieldReportedDate,
	FieldCollectedDate,
	FieldPcrTotalTests,
	FieldPrTotalTests,
	FieldAgTotalTests,
	FieldPcrPositiveTests,
	FieldPrPositiveTests,
	FieldAgPositiveTests,
}

var (
	// PlacesPrimaryKey and PlacesColumn2 are the table columns denoting the
	// primary key for the places relation (M2M).
	PlacesPrimaryKey = []string{"infected_record_id", "place_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
