// Code generated by entc, DO NOT EDIT.

package place

import (
	"opencensus/core/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKind), v))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Politic applies equality check predicate on the "politic" field. It's identical to PoliticEQ.
func Politic(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPolitic), v))
	})
}

// Ubigeo applies equality check predicate on the "ubigeo" field. It's identical to UbigeoEQ.
func Ubigeo(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUbigeo), v))
	})
}

// CovidZone applies equality check predicate on the "covidZone" field. It's identical to CovidZoneEQ.
func CovidZone(v bool) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCovidZone), v))
	})
}

// Lat applies equality check predicate on the "lat" field. It's identical to LatEQ.
func Lat(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLat), v))
	})
}

// Lon applies equality check predicate on the "lon" field. It's identical to LonEQ.
func Lon(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLon), v))
	})
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKind), v))
	})
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldKind), v))
	})
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldKind), v...))
	})
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldKind), v...))
	})
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldKind), v))
	})
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldKind), v))
	})
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldKind), v))
	})
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldKind), v))
	})
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldKind), v))
	})
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldKind), v))
	})
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldKind), v))
	})
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldKind), v))
	})
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldKind), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// PoliticEQ applies the EQ predicate on the "politic" field.
func PoliticEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPolitic), v))
	})
}

// PoliticNEQ applies the NEQ predicate on the "politic" field.
func PoliticNEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPolitic), v))
	})
}

// PoliticIn applies the In predicate on the "politic" field.
func PoliticIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPolitic), v...))
	})
}

// PoliticNotIn applies the NotIn predicate on the "politic" field.
func PoliticNotIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPolitic), v...))
	})
}

// PoliticGT applies the GT predicate on the "politic" field.
func PoliticGT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPolitic), v))
	})
}

// PoliticGTE applies the GTE predicate on the "politic" field.
func PoliticGTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPolitic), v))
	})
}

// PoliticLT applies the LT predicate on the "politic" field.
func PoliticLT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPolitic), v))
	})
}

// PoliticLTE applies the LTE predicate on the "politic" field.
func PoliticLTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPolitic), v))
	})
}

// PoliticContains applies the Contains predicate on the "politic" field.
func PoliticContains(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPolitic), v))
	})
}

// PoliticHasPrefix applies the HasPrefix predicate on the "politic" field.
func PoliticHasPrefix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPolitic), v))
	})
}

// PoliticHasSuffix applies the HasSuffix predicate on the "politic" field.
func PoliticHasSuffix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPolitic), v))
	})
}

// PoliticIsNil applies the IsNil predicate on the "politic" field.
func PoliticIsNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldPolitic)))
	})
}

// PoliticNotNil applies the NotNil predicate on the "politic" field.
func PoliticNotNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldPolitic)))
	})
}

// PoliticEqualFold applies the EqualFold predicate on the "politic" field.
func PoliticEqualFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPolitic), v))
	})
}

// PoliticContainsFold applies the ContainsFold predicate on the "politic" field.
func PoliticContainsFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPolitic), v))
	})
}

// UbigeoEQ applies the EQ predicate on the "ubigeo" field.
func UbigeoEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUbigeo), v))
	})
}

// UbigeoNEQ applies the NEQ predicate on the "ubigeo" field.
func UbigeoNEQ(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUbigeo), v))
	})
}

// UbigeoIn applies the In predicate on the "ubigeo" field.
func UbigeoIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUbigeo), v...))
	})
}

// UbigeoNotIn applies the NotIn predicate on the "ubigeo" field.
func UbigeoNotIn(vs ...string) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUbigeo), v...))
	})
}

// UbigeoGT applies the GT predicate on the "ubigeo" field.
func UbigeoGT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUbigeo), v))
	})
}

// UbigeoGTE applies the GTE predicate on the "ubigeo" field.
func UbigeoGTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUbigeo), v))
	})
}

// UbigeoLT applies the LT predicate on the "ubigeo" field.
func UbigeoLT(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUbigeo), v))
	})
}

// UbigeoLTE applies the LTE predicate on the "ubigeo" field.
func UbigeoLTE(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUbigeo), v))
	})
}

// UbigeoContains applies the Contains predicate on the "ubigeo" field.
func UbigeoContains(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldUbigeo), v))
	})
}

// UbigeoHasPrefix applies the HasPrefix predicate on the "ubigeo" field.
func UbigeoHasPrefix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldUbigeo), v))
	})
}

// UbigeoHasSuffix applies the HasSuffix predicate on the "ubigeo" field.
func UbigeoHasSuffix(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldUbigeo), v))
	})
}

// UbigeoIsNil applies the IsNil predicate on the "ubigeo" field.
func UbigeoIsNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldUbigeo)))
	})
}

// UbigeoNotNil applies the NotNil predicate on the "ubigeo" field.
func UbigeoNotNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldUbigeo)))
	})
}

// UbigeoEqualFold applies the EqualFold predicate on the "ubigeo" field.
func UbigeoEqualFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldUbigeo), v))
	})
}

// UbigeoContainsFold applies the ContainsFold predicate on the "ubigeo" field.
func UbigeoContainsFold(v string) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldUbigeo), v))
	})
}

// CovidZoneEQ applies the EQ predicate on the "covidZone" field.
func CovidZoneEQ(v bool) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCovidZone), v))
	})
}

// CovidZoneNEQ applies the NEQ predicate on the "covidZone" field.
func CovidZoneNEQ(v bool) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCovidZone), v))
	})
}

// CovidZoneIsNil applies the IsNil predicate on the "covidZone" field.
func CovidZoneIsNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCovidZone)))
	})
}

// CovidZoneNotNil applies the NotNil predicate on the "covidZone" field.
func CovidZoneNotNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCovidZone)))
	})
}

// LatEQ applies the EQ predicate on the "lat" field.
func LatEQ(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLat), v))
	})
}

// LatNEQ applies the NEQ predicate on the "lat" field.
func LatNEQ(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLat), v))
	})
}

// LatIn applies the In predicate on the "lat" field.
func LatIn(vs ...float64) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLat), v...))
	})
}

// LatNotIn applies the NotIn predicate on the "lat" field.
func LatNotIn(vs ...float64) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLat), v...))
	})
}

// LatGT applies the GT predicate on the "lat" field.
func LatGT(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLat), v))
	})
}

// LatGTE applies the GTE predicate on the "lat" field.
func LatGTE(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLat), v))
	})
}

// LatLT applies the LT predicate on the "lat" field.
func LatLT(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLat), v))
	})
}

// LatLTE applies the LTE predicate on the "lat" field.
func LatLTE(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLat), v))
	})
}

// LatIsNil applies the IsNil predicate on the "lat" field.
func LatIsNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLat)))
	})
}

// LatNotNil applies the NotNil predicate on the "lat" field.
func LatNotNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLat)))
	})
}

// LonEQ applies the EQ predicate on the "lon" field.
func LonEQ(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLon), v))
	})
}

// LonNEQ applies the NEQ predicate on the "lon" field.
func LonNEQ(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLon), v))
	})
}

// LonIn applies the In predicate on the "lon" field.
func LonIn(vs ...float64) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLon), v...))
	})
}

// LonNotIn applies the NotIn predicate on the "lon" field.
func LonNotIn(vs ...float64) predicate.Place {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Place(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLon), v...))
	})
}

// LonGT applies the GT predicate on the "lon" field.
func LonGT(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLon), v))
	})
}

// LonGTE applies the GTE predicate on the "lon" field.
func LonGTE(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLon), v))
	})
}

// LonLT applies the LT predicate on the "lon" field.
func LonLT(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLon), v))
	})
}

// LonLTE applies the LTE predicate on the "lon" field.
func LonLTE(v float64) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLon), v))
	})
}

// LonIsNil applies the IsNil predicate on the "lon" field.
func LonIsNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLon)))
	})
}

// LonNotNil applies the NotNil predicate on the "lon" field.
func LonNotNil() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLon)))
	})
}

// HasOxygenrecords applies the HasEdge predicate on the "oxygenrecords" edge.
func HasOxygenrecords() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OxygenrecordsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, OxygenrecordsTable, OxygenrecordsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOxygenrecordsWith applies the HasEdge predicate on the "oxygenrecords" edge with a given conditions (other predicates).
func HasOxygenrecordsWith(preds ...predicate.OxygenRecord) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OxygenrecordsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, OxygenrecordsTable, OxygenrecordsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBedRecords applies the HasEdge predicate on the "bedRecords" edge.
func HasBedRecords() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BedRecordsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, BedRecordsTable, BedRecordsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBedRecordsWith applies the HasEdge predicate on the "bedRecords" edge with a given conditions (other predicates).
func HasBedRecordsWith(preds ...predicate.BedRecord) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BedRecordsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, BedRecordsTable, BedRecordsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeathRecords applies the HasEdge predicate on the "deathRecords" edge.
func HasDeathRecords() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DeathRecordsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, DeathRecordsTable, DeathRecordsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeathRecordsWith applies the HasEdge predicate on the "deathRecords" edge with a given conditions (other predicates).
func HasDeathRecordsWith(preds ...predicate.DeathRecord) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DeathRecordsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, DeathRecordsTable, DeathRecordsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInfectedRecords applies the HasEdge predicate on the "infectedRecords" edge.
func HasInfectedRecords() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InfectedRecordsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, InfectedRecordsTable, InfectedRecordsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInfectedRecordsWith applies the HasEdge predicate on the "infectedRecords" edge with a given conditions (other predicates).
func HasInfectedRecordsWith(preds ...predicate.InfectedRecord) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InfectedRecordsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, InfectedRecordsTable, InfectedRecordsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRegion applies the HasEdge predicate on the "region" edge.
func HasRegion() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RegionTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RegionTable, RegionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRegionWith applies the HasEdge predicate on the "region" edge with a given conditions (other predicates).
func HasRegionWith(preds ...predicate.Region) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RegionInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RegionTable, RegionColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProvince applies the HasEdge predicate on the "province" edge.
func HasProvince() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProvinceTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProvinceTable, ProvinceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProvinceWith applies the HasEdge predicate on the "province" edge with a given conditions (other predicates).
func HasProvinceWith(preds ...predicate.Province) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProvinceInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProvinceTable, ProvinceColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDistrict applies the HasEdge predicate on the "district" edge.
func HasDistrict() predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DistrictTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DistrictTable, DistrictColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDistrictWith applies the HasEdge predicate on the "district" edge with a given conditions (other predicates).
func HasDistrictWith(preds ...predicate.District) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DistrictInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DistrictTable, DistrictColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Place) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Place) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Place) predicate.Place {
	return predicate.Place(func(s *sql.Selector) {
		p(s.Not())
	})
}
