// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"opencensus/core/ent/bedrecord"
	"opencensus/core/ent/place"
	"opencensus/core/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BedRecordUpdate is the builder for updating BedRecord entities.
type BedRecordUpdate struct {
	config
	hooks    []Hook
	mutation *BedRecordMutation
}

// Where adds a new predicate for the BedRecordUpdate builder.
func (bru *BedRecordUpdate) Where(ps ...predicate.BedRecord) *BedRecordUpdate {
	bru.mutation.predicates = append(bru.mutation.predicates, ps...)
	return bru
}

// SetReportedDate sets the "reportedDate" field.
func (bru *BedRecordUpdate) SetReportedDate(t time.Time) *BedRecordUpdate {
	bru.mutation.SetReportedDate(t)
	return bru
}

// SetCollectedDate sets the "collectedDate" field.
func (bru *BedRecordUpdate) SetCollectedDate(t time.Time) *BedRecordUpdate {
	bru.mutation.SetCollectedDate(t)
	return bru
}

// SetBusyBeds sets the "busyBeds" field.
func (bru *BedRecordUpdate) SetBusyBeds(i int) *BedRecordUpdate {
	bru.mutation.ResetBusyBeds()
	bru.mutation.SetBusyBeds(i)
	return bru
}

// AddBusyBeds adds i to the "busyBeds" field.
func (bru *BedRecordUpdate) AddBusyBeds(i int) *BedRecordUpdate {
	bru.mutation.AddBusyBeds(i)
	return bru
}

// SetAvailableBeds sets the "availableBeds" field.
func (bru *BedRecordUpdate) SetAvailableBeds(i int) *BedRecordUpdate {
	bru.mutation.ResetAvailableBeds()
	bru.mutation.SetAvailableBeds(i)
	return bru
}

// AddAvailableBeds adds i to the "availableBeds" field.
func (bru *BedRecordUpdate) AddAvailableBeds(i int) *BedRecordUpdate {
	bru.mutation.AddAvailableBeds(i)
	return bru
}

// SetTotalBeds sets the "totalBeds" field.
func (bru *BedRecordUpdate) SetTotalBeds(i int) *BedRecordUpdate {
	bru.mutation.ResetTotalBeds()
	bru.mutation.SetTotalBeds(i)
	return bru
}

// AddTotalBeds adds i to the "totalBeds" field.
func (bru *BedRecordUpdate) AddTotalBeds(i int) *BedRecordUpdate {
	bru.mutation.AddTotalBeds(i)
	return bru
}

// SetKindBed sets the "kindBed" field.
func (bru *BedRecordUpdate) SetKindBed(s string) *BedRecordUpdate {
	bru.mutation.SetKindBed(s)
	return bru
}

// SetKindAge sets the "kindAge" field.
func (bru *BedRecordUpdate) SetKindAge(s string) *BedRecordUpdate {
	bru.mutation.SetKindAge(s)
	return bru
}

// AddPlaceIDs adds the "places" edge to the Place entity by IDs.
func (bru *BedRecordUpdate) AddPlaceIDs(ids ...int) *BedRecordUpdate {
	bru.mutation.AddPlaceIDs(ids...)
	return bru
}

// AddPlaces adds the "places" edges to the Place entity.
func (bru *BedRecordUpdate) AddPlaces(p ...*Place) *BedRecordUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return bru.AddPlaceIDs(ids...)
}

// Mutation returns the BedRecordMutation object of the builder.
func (bru *BedRecordUpdate) Mutation() *BedRecordMutation {
	return bru.mutation
}

// ClearPlaces clears all "places" edges to the Place entity.
func (bru *BedRecordUpdate) ClearPlaces() *BedRecordUpdate {
	bru.mutation.ClearPlaces()
	return bru
}

// RemovePlaceIDs removes the "places" edge to Place entities by IDs.
func (bru *BedRecordUpdate) RemovePlaceIDs(ids ...int) *BedRecordUpdate {
	bru.mutation.RemovePlaceIDs(ids...)
	return bru
}

// RemovePlaces removes "places" edges to Place entities.
func (bru *BedRecordUpdate) RemovePlaces(p ...*Place) *BedRecordUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return bru.RemovePlaceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bru *BedRecordUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bru.hooks) == 0 {
		affected, err = bru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BedRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bru.mutation = mutation
			affected, err = bru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bru.hooks) - 1; i >= 0; i-- {
			mut = bru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bru *BedRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := bru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bru *BedRecordUpdate) Exec(ctx context.Context) error {
	_, err := bru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bru *BedRecordUpdate) ExecX(ctx context.Context) {
	if err := bru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bru *BedRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bedrecord.Table,
			Columns: bedrecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bedrecord.FieldID,
			},
		},
	}
	if ps := bru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bru.mutation.ReportedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bedrecord.FieldReportedDate,
		})
	}
	if value, ok := bru.mutation.CollectedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bedrecord.FieldCollectedDate,
		})
	}
	if value, ok := bru.mutation.BusyBeds(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldBusyBeds,
		})
	}
	if value, ok := bru.mutation.AddedBusyBeds(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldBusyBeds,
		})
	}
	if value, ok := bru.mutation.AvailableBeds(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldAvailableBeds,
		})
	}
	if value, ok := bru.mutation.AddedAvailableBeds(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldAvailableBeds,
		})
	}
	if value, ok := bru.mutation.TotalBeds(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldTotalBeds,
		})
	}
	if value, ok := bru.mutation.AddedTotalBeds(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldTotalBeds,
		})
	}
	if value, ok := bru.mutation.KindBed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bedrecord.FieldKindBed,
		})
	}
	if value, ok := bru.mutation.KindAge(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bedrecord.FieldKindAge,
		})
	}
	if bru.mutation.PlacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bedrecord.PlacesTable,
			Columns: bedrecord.PlacesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bru.mutation.RemovedPlacesIDs(); len(nodes) > 0 && !bru.mutation.PlacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bedrecord.PlacesTable,
			Columns: bedrecord.PlacesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bru.mutation.PlacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bedrecord.PlacesTable,
			Columns: bedrecord.PlacesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bedrecord.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BedRecordUpdateOne is the builder for updating a single BedRecord entity.
type BedRecordUpdateOne struct {
	config
	hooks    []Hook
	mutation *BedRecordMutation
}

// SetReportedDate sets the "reportedDate" field.
func (bruo *BedRecordUpdateOne) SetReportedDate(t time.Time) *BedRecordUpdateOne {
	bruo.mutation.SetReportedDate(t)
	return bruo
}

// SetCollectedDate sets the "collectedDate" field.
func (bruo *BedRecordUpdateOne) SetCollectedDate(t time.Time) *BedRecordUpdateOne {
	bruo.mutation.SetCollectedDate(t)
	return bruo
}

// SetBusyBeds sets the "busyBeds" field.
func (bruo *BedRecordUpdateOne) SetBusyBeds(i int) *BedRecordUpdateOne {
	bruo.mutation.ResetBusyBeds()
	bruo.mutation.SetBusyBeds(i)
	return bruo
}

// AddBusyBeds adds i to the "busyBeds" field.
func (bruo *BedRecordUpdateOne) AddBusyBeds(i int) *BedRecordUpdateOne {
	bruo.mutation.AddBusyBeds(i)
	return bruo
}

// SetAvailableBeds sets the "availableBeds" field.
func (bruo *BedRecordUpdateOne) SetAvailableBeds(i int) *BedRecordUpdateOne {
	bruo.mutation.ResetAvailableBeds()
	bruo.mutation.SetAvailableBeds(i)
	return bruo
}

// AddAvailableBeds adds i to the "availableBeds" field.
func (bruo *BedRecordUpdateOne) AddAvailableBeds(i int) *BedRecordUpdateOne {
	bruo.mutation.AddAvailableBeds(i)
	return bruo
}

// SetTotalBeds sets the "totalBeds" field.
func (bruo *BedRecordUpdateOne) SetTotalBeds(i int) *BedRecordUpdateOne {
	bruo.mutation.ResetTotalBeds()
	bruo.mutation.SetTotalBeds(i)
	return bruo
}

// AddTotalBeds adds i to the "totalBeds" field.
func (bruo *BedRecordUpdateOne) AddTotalBeds(i int) *BedRecordUpdateOne {
	bruo.mutation.AddTotalBeds(i)
	return bruo
}

// SetKindBed sets the "kindBed" field.
func (bruo *BedRecordUpdateOne) SetKindBed(s string) *BedRecordUpdateOne {
	bruo.mutation.SetKindBed(s)
	return bruo
}

// SetKindAge sets the "kindAge" field.
func (bruo *BedRecordUpdateOne) SetKindAge(s string) *BedRecordUpdateOne {
	bruo.mutation.SetKindAge(s)
	return bruo
}

// AddPlaceIDs adds the "places" edge to the Place entity by IDs.
func (bruo *BedRecordUpdateOne) AddPlaceIDs(ids ...int) *BedRecordUpdateOne {
	bruo.mutation.AddPlaceIDs(ids...)
	return bruo
}

// AddPlaces adds the "places" edges to the Place entity.
func (bruo *BedRecordUpdateOne) AddPlaces(p ...*Place) *BedRecordUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return bruo.AddPlaceIDs(ids...)
}

// Mutation returns the BedRecordMutation object of the builder.
func (bruo *BedRecordUpdateOne) Mutation() *BedRecordMutation {
	return bruo.mutation
}

// ClearPlaces clears all "places" edges to the Place entity.
func (bruo *BedRecordUpdateOne) ClearPlaces() *BedRecordUpdateOne {
	bruo.mutation.ClearPlaces()
	return bruo
}

// RemovePlaceIDs removes the "places" edge to Place entities by IDs.
func (bruo *BedRecordUpdateOne) RemovePlaceIDs(ids ...int) *BedRecordUpdateOne {
	bruo.mutation.RemovePlaceIDs(ids...)
	return bruo
}

// RemovePlaces removes "places" edges to Place entities.
func (bruo *BedRecordUpdateOne) RemovePlaces(p ...*Place) *BedRecordUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return bruo.RemovePlaceIDs(ids...)
}

// Save executes the query and returns the updated BedRecord entity.
func (bruo *BedRecordUpdateOne) Save(ctx context.Context) (*BedRecord, error) {
	var (
		err  error
		node *BedRecord
	)
	if len(bruo.hooks) == 0 {
		node, err = bruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BedRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bruo.mutation = mutation
			node, err = bruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bruo.hooks) - 1; i >= 0; i-- {
			mut = bruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (bruo *BedRecordUpdateOne) SaveX(ctx context.Context) *BedRecord {
	node, err := bruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bruo *BedRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := bruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bruo *BedRecordUpdateOne) ExecX(ctx context.Context) {
	if err := bruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bruo *BedRecordUpdateOne) sqlSave(ctx context.Context) (_node *BedRecord, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bedrecord.Table,
			Columns: bedrecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bedrecord.FieldID,
			},
		},
	}
	id, ok := bruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing BedRecord.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := bruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bruo.mutation.ReportedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bedrecord.FieldReportedDate,
		})
	}
	if value, ok := bruo.mutation.CollectedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bedrecord.FieldCollectedDate,
		})
	}
	if value, ok := bruo.mutation.BusyBeds(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldBusyBeds,
		})
	}
	if value, ok := bruo.mutation.AddedBusyBeds(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldBusyBeds,
		})
	}
	if value, ok := bruo.mutation.AvailableBeds(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldAvailableBeds,
		})
	}
	if value, ok := bruo.mutation.AddedAvailableBeds(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldAvailableBeds,
		})
	}
	if value, ok := bruo.mutation.TotalBeds(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldTotalBeds,
		})
	}
	if value, ok := bruo.mutation.AddedTotalBeds(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bedrecord.FieldTotalBeds,
		})
	}
	if value, ok := bruo.mutation.KindBed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bedrecord.FieldKindBed,
		})
	}
	if value, ok := bruo.mutation.KindAge(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bedrecord.FieldKindAge,
		})
	}
	if bruo.mutation.PlacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bedrecord.PlacesTable,
			Columns: bedrecord.PlacesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bruo.mutation.RemovedPlacesIDs(); len(nodes) > 0 && !bruo.mutation.PlacesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bedrecord.PlacesTable,
			Columns: bedrecord.PlacesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bruo.mutation.PlacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bedrecord.PlacesTable,
			Columns: bedrecord.PlacesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: place.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BedRecord{config: bruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bedrecord.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
