// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"opencensus/core/ent/infectedrecord"
	"opencensus/core/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InfectedRecordDelete is the builder for deleting a InfectedRecord entity.
type InfectedRecordDelete struct {
	config
	hooks    []Hook
	mutation *InfectedRecordMutation
}

// Where adds a new predicate to the InfectedRecordDelete builder.
func (ird *InfectedRecordDelete) Where(ps ...predicate.InfectedRecord) *InfectedRecordDelete {
	ird.mutation.predicates = append(ird.mutation.predicates, ps...)
	return ird
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ird *InfectedRecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ird.hooks) == 0 {
		affected, err = ird.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InfectedRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ird.mutation = mutation
			affected, err = ird.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ird.hooks) - 1; i >= 0; i-- {
			mut = ird.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ird.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ird *InfectedRecordDelete) ExecX(ctx context.Context) int {
	n, err := ird.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ird *InfectedRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: infectedrecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: infectedrecord.FieldID,
			},
		},
	}
	if ps := ird.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ird.driver, _spec)
}

// InfectedRecordDeleteOne is the builder for deleting a single InfectedRecord entity.
type InfectedRecordDeleteOne struct {
	ird *InfectedRecordDelete
}

// Exec executes the deletion query.
func (irdo *InfectedRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := irdo.ird.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{infectedrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (irdo *InfectedRecordDeleteOne) ExecX(ctx context.Context) {
	irdo.ird.ExecX(ctx)
}
