// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"opencensus/core/ent/oxygenrecord"
	"opencensus/core/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OxygenRecordDelete is the builder for deleting a OxygenRecord entity.
type OxygenRecordDelete struct {
	config
	hooks    []Hook
	mutation *OxygenRecordMutation
}

// Where adds a new predicate to the OxygenRecordDelete builder.
func (ord *OxygenRecordDelete) Where(ps ...predicate.OxygenRecord) *OxygenRecordDelete {
	ord.mutation.predicates = append(ord.mutation.predicates, ps...)
	return ord
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ord *OxygenRecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ord.hooks) == 0 {
		affected, err = ord.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OxygenRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ord.mutation = mutation
			affected, err = ord.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ord.hooks) - 1; i >= 0; i-- {
			mut = ord.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ord.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ord *OxygenRecordDelete) ExecX(ctx context.Context) int {
	n, err := ord.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ord *OxygenRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: oxygenrecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oxygenrecord.FieldID,
			},
		},
	}
	if ps := ord.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ord.driver, _spec)
}

// OxygenRecordDeleteOne is the builder for deleting a single OxygenRecord entity.
type OxygenRecordDeleteOne struct {
	ord *OxygenRecordDelete
}

// Exec executes the deletion query.
func (ordo *OxygenRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := ordo.ord.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oxygenrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ordo *OxygenRecordDeleteOne) ExecX(ctx context.Context) {
	ordo.ord.ExecX(ctx)
}
