// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opencensus/core/ent/district"
	"opencensus/core/ent/organization"
	"opencensus/core/ent/province"
	"opencensus/core/ent/region"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProvinceCreate is the builder for creating a Province entity.
type ProvinceCreate struct {
	config
	mutation *ProvinceMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *ProvinceCreate) SetName(s string) *ProvinceCreate {
	pc.mutation.SetName(s)
	return pc
}

// AddOrganizationIDs adds the "organization" edge to the Organization entity by IDs.
func (pc *ProvinceCreate) AddOrganizationIDs(ids ...int) *ProvinceCreate {
	pc.mutation.AddOrganizationIDs(ids...)
	return pc
}

// AddOrganization adds the "organization" edges to the Organization entity.
func (pc *ProvinceCreate) AddOrganization(o ...*Organization) *ProvinceCreate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pc.AddOrganizationIDs(ids...)
}

// AddRegionIDs adds the "region" edge to the Region entity by IDs.
func (pc *ProvinceCreate) AddRegionIDs(ids ...int) *ProvinceCreate {
	pc.mutation.AddRegionIDs(ids...)
	return pc
}

// AddRegion adds the "region" edges to the Region entity.
func (pc *ProvinceCreate) AddRegion(r ...*Region) *ProvinceCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pc.AddRegionIDs(ids...)
}

// AddDistrictIDs adds the "district" edge to the District entity by IDs.
func (pc *ProvinceCreate) AddDistrictIDs(ids ...int) *ProvinceCreate {
	pc.mutation.AddDistrictIDs(ids...)
	return pc
}

// AddDistrict adds the "district" edges to the District entity.
func (pc *ProvinceCreate) AddDistrict(d ...*District) *ProvinceCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pc.AddDistrictIDs(ids...)
}

// Mutation returns the ProvinceMutation object of the builder.
func (pc *ProvinceCreate) Mutation() *ProvinceMutation {
	return pc.mutation
}

// Save creates the Province in the database.
func (pc *ProvinceCreate) Save(ctx context.Context) (*Province, error) {
	var (
		err  error
		node *Province
	)
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProvinceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProvinceCreate) SaveX(ctx context.Context) *Province {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProvinceCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	return nil
}

func (pc *ProvinceCreate) sqlSave(ctx context.Context) (*Province, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pc *ProvinceCreate) createSpec() (*Province, *sqlgraph.CreateSpec) {
	var (
		_node = &Province{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: province.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: province.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: province.FieldName,
		})
		_node.Name = value
	}
	if nodes := pc.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   province.OrganizationTable,
			Columns: province.OrganizationPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: organization.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.RegionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   province.RegionTable,
			Columns: province.RegionPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: region.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   province.DistrictTable,
			Columns: province.DistrictPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: district.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProvinceCreateBulk is the builder for creating many Province entities in bulk.
type ProvinceCreateBulk struct {
	config
	builders []*ProvinceCreate
}

// Save creates the Province entities in the database.
func (pcb *ProvinceCreateBulk) Save(ctx context.Context) ([]*Province, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Province, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProvinceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProvinceCreateBulk) SaveX(ctx context.Context) []*Province {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
