// Code generated by entc, DO NOT EDIT.

package province

const (
	// Label holds the string label denoting the province type in the database.
	Label = "province"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgePlaces holds the string denoting the places edge name in mutations.
	EdgePlaces = "places"
	// EdgeRegions holds the string denoting the regions edge name in mutations.
	EdgeRegions = "regions"
	// EdgeDistricts holds the string denoting the districts edge name in mutations.
	EdgeDistricts = "districts"

	// Table holds the table name of the province in the database.
	Table = "provinces"
	// PlacesTable is the table the holds the places relation/edge. The primary key declared below.
	PlacesTable = "place_provinces"
	// PlacesInverseTable is the table name for the Place entity.
	// It exists in this package in order to avoid circular dependency with the "place" package.
	PlacesInverseTable = "places"
	// RegionsTable is the table the holds the regions relation/edge. The primary key declared below.
	RegionsTable = "region_provinces"
	// RegionsInverseTable is the table name for the Region entity.
	// It exists in this package in order to avoid circular dependency with the "region" package.
	RegionsInverseTable = "regions"
	// DistrictsTable is the table the holds the districts relation/edge. The primary key declared below.
	DistrictsTable = "province_districts"
	// DistrictsInverseTable is the table name for the District entity.
	// It exists in this package in order to avoid circular dependency with the "district" package.
	DistrictsInverseTable = "districts"
)

// Columns holds all SQL columns for province fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// PlacesPrimaryKey and PlacesColumn2 are the table columns denoting the
	// primary key for the places relation (M2M).
	PlacesPrimaryKey = []string{"place_id", "province_id"}
	// RegionsPrimaryKey and RegionsColumn2 are the table columns denoting the
	// primary key for the regions relation (M2M).
	RegionsPrimaryKey = []string{"region_id", "province_id"}
	// DistrictsPrimaryKey and DistrictsColumn2 are the table columns denoting the
	// primary key for the districts relation (M2M).
	DistrictsPrimaryKey = []string{"province_id", "district_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
