// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BedRecord is the predicate function for bedrecord builders.
type BedRecord func(*sql.Selector)

// District is the predicate function for district builders.
type District func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OxygenRecord is the predicate function for oxygenrecord builders.
type OxygenRecord func(*sql.Selector)

// Province is the predicate function for province builders.
type Province func(*sql.Selector)

// Region is the predicate function for region builders.
type Region func(*sql.Selector)
